# Datei: webserver/traefik/docker-compose.yml
version: '3'

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.4
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - ./traefik_api.yml:/traefik_api.yml
      - ./acme.json:/acme.json
networks:
  web:
    external: true

