# Datei: webserver/traefik/traefik.yml
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
api:
  dashboard: true
certificatesResolvers:
  lets-encrypt:
    acme:
      email: info@dockerbuch.info
      storage: acme.json
      tlsChallenge: {}
providers:
  docker:
    watch: true
    network: web
  file:
    filename: traefik_api.yml

