# Datei: webserver/traefik/me/docker-compose.yml
version: '3'
services:
  buch:
    image: nginx:1
    networks:
      - default
      - web
    labels:
      - traefik.http.routers.buch.rule=Host(`me.dockerbuch.info`)
      - traefik.http.routers.buch.tls=true
      - traefik.http.routers.buch.tls.certresolver=lets-encrypt
      - traefik.http.services.buch.loadbalancer.server.port=80
networks:
  web:
    external: true
